### ISSUE TITLE
javax.net.ssl.SSLHandshakeException on Java 11 (PaperMC)

### ISSUE THREAD

**Issue by JONTTM** [jacobtread/ServerJars-Updater#5]
Host: https://server.pro/
Plan: Pro - High (6 GB)

serverjars.properties
```
type=paper
version=latest
```

JVM Flags
```
-Xms5120M -Xmx5120M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Djava.system.class.loader=com.serverjars.updater.ServerJarsLoader -jar Updater-2.1.jar
```

Java 11 - HotSpot
```
#==============================================================#
_____ __
/ ___/___ ______ _____ _____ / /___ ___________
\__ \/ _ \/ ___/ | / / _ \/ ___/_ / / __ `/ ___/ ___/
___/ / __/ / | |/ / __/ / / /_/ / /_/ / / (__ )
/____/\___/_/ |___/\___/_/ \____/\__,_/_/ /____/
ServerJars.com Made with love by Songoda <3
#==============================================================#
Loading properties file
Loaded properties file
#==============================================================#
Checking if jar is up to date
#==============================================================#
Jar missing! downloading 'latest' of 'paper'
#==============================================================#
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
at com.serverjars.api.ServerJars.sendRequest(ServerJars.java:50)
at com.serverjars.api.request.JarRequest.send(JarRequest.java:65)
at com.serverjars.updater.Updater.downloadJar(Updater.java:180)
at com.serverjars.updater.Updater.checkUpdates(Updater.java:106)
at com.serverjars.updater.Updater.main(Updater.java:72)
Exception in thread "main" java.lang.NullPointerException
at com.serverjars.api.Response.isSuccess(Response.java:18)
at com.serverjars.updater.Updater.downloadJar(Updater.java:181)
at com.serverjars.updater.Updater.checkUpdates(Updater.java:106)
at com.serverjars.updater.Updater.main(Updater.java:72)
```

Java 8 - HotSpot
```
#==============================================================#
_____ __
/ ___/___ ______ _____ _____ / /___ ___________
\__ \/ _ \/ ___/ | / / _ \/ ___/_ / / __ `/ ___/ ___/
___/ / __/ / | |/ / __/ / / /_/ / /_/ / / (__ )
/____/\___/_/ |___/\___/_/ \____/\__,_/_/ /____/
ServerJars.com Made with love by Songoda <3
#==============================================================#
Loading properties file
Loaded properties file
#==============================================================#
Checking if jar is up to date
#==============================================================#
Jar missing! downloading 'latest' of 'paper'
#==============================================================#
#==============================================================#
Jar downloaded successfully
#==============================================================#
#==============================================================#
Starting 'paper' version 'latest'
#==============================================================#
Downloading vanilla jar...
Patching vanilla jar...
System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.212-b03) Host: Linux 5.4.0-58-generic (amd64)
Loading libraries, please wait...
[INFO] Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[INFO] Found new data pack file/bukkit, loading it automatically
[INFO] Reloading ResourceManager: Default, bukkit
[INFO] Loaded 7 recipes
[INFO] Starting minecraft server version 1.16.4
[INFO] Loading properties
[INFO] .... This server is running Paper version git-Paper-366 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[INFO] .... Server Ping Player Sample Count: 12
[INFO] .... Using 4 threads for Netty based IO
[INFO] .... Debug logging is disabled
[INFO] .... Default game type: SURVIVAL
[INFO] .... Generating keypair
[INFO] .... Starting Minecraft server on *:25565
[INFO] .... Using epoll channel type
[INFO] .... Preparing level "world"
[WARNING] .... Unable to find spawn biome
[WARNING] .... Unable to find spawn biome
[INFO] .... Preparing start region for dimension minecraft:overworld
[INFO] .... Loaded 0 spawn chunks for world world
[INFO] .... Preparing spawn area: 0%
[INFO] .... Time elapsed: 353 ms
[INFO] .... Preparing start region for dimension minecraft:the_nether
[INFO] .... Loaded 0 spawn chunks for world world_nether
[INFO] .... Time elapsed: 252 ms
[INFO] .... Preparing start region for dimension minecraft:the_end
[INFO] .... Loaded 0 spawn chunks for world world_the_end
[INFO] .... Time elapsed: 154 ms
[INFO] .... Starting GS4 status listener
[INFO] .... Thread Query Listener started
[INFO] .... Query running on 0.0.0.0:25565
[INFO] .... Running delayed init tasks
[INFO] .... Done (5.527s)! For help, type "help"
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] *
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] *
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_212
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] *
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information:
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] * https://papermc.io/java11
[WARNING] .... [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[INFO] .... Timings Reset
```

This worries me because Paper will stop supporting Java 8 in the near future as mentioned in the warning from the console.

**Comment by JONTTM** [comment]
Closed because repo has been moved to https://github.com/ServerJars/updater
